### ISSUE TITLE
cannot import name Class_szfast

### ISSUE THREAD

**Issue by ShimingGu** [CLASS-SZ/class_sz#1]
Hi,
 
When I tried to import class_sz I met this issue attached below. How can I fix this issue?
 
Many Thanks,
 
Shiming

```
from classy_sz import Class
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 from classy_sz import Class

File ~/class_sz/python/classy.pyx:37, in init classy_sz()

ImportError: cannot import name Class_szfast
```

**Comment by borisbolliet** [comment]
Hi Shiming, 


Have you followed the install instructions for the python wrapper? 

Also check the colab notebook [here](https://colab.research.google.com/drive/1AULgG4ZLLG1YXRI86L54-hpjWyl1X-8c?usp=sharing), let me know if you still have issues!

The key install instructions (if you run on linux/ubuntu) are:
```
cd class_sz
mv Makefile Makefile_os
mv Makefile_linux Makefile
make clean
make
cd python
pip install -e .
cd classy_szfast
pip install -e .
```

PS: very sorry for the slow response!

**Comment by borisbolliet** [comment]
@ShimingGu  closing this issue for now, assuming this is solved. Please let me know if that is not the case.
